name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'android-terminal/**'
      - '.github/workflows/android-ci.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'android-terminal/**'
      - '.github/workflows/android-ci.yml'

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android platform and build tools
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses
      - name: Install NDK and CMake
        run: |
          sdkmanager --install "ndk;25.2.9519653" "cmake;3.22.1"

      - name: Generate Gradle wrapper (8.7)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
          build-root-directory: android-terminal
          arguments: wrapper

      - name: Build Debug APK with ./gradlew
        working-directory: android-terminal
        run: |
          chmod +x ./gradlew
          ./gradlew --no-daemon \
            -Dorg.gradle.caching=false \
            -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8" \
            assembleDebug --stacktrace \
            -Pandroid.ndkVersion=25.2.9519653 \
            -Pandroid.cmake.version=3.22.1

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: CanvasTerminal-android-debug
          path: android-terminal/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
